services:
  - type: web
    name: crud-academico
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn portal_academico.wsgi"
